const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const code=fs.readFileSync('app.js','utf8');
const now=new Date();
const values={'filter-mode':'and','rs-min':'','rs-period':'20','liquidity-min':'','close-min':''};
let types=['relative-strength','liquidity','strong-close'];
const context=vm.createContext({Date,Intl,watchlist:new Set(),assetKey:()=>'',document:{querySelector:id=>({value:values[id.slice(1)]??'',checked:false}),querySelectorAll:()=>types.map(value=>({value}))}});
vm.runInContext(code.slice(code.indexOf('function qualityFresh'),code.indexOf('function render')),context);
const date=new Date(now);date.setUTCDate(date.getUTCDate()-1);
const asset={market:'Crypto',priceDate:date.toISOString().slice(0,10),snapshotAt:now.toISOString(),relativeStrength20:5,relativeStrength60:2,avgTurnover20:6e6,liquidityCurrency:'USD',closeLocation:.8,signals:types.map(type=>({type}))};
assert.equal(context.matchesFilters(asset),true);
assert.equal(context.matchesFilters({...asset,historyStale:true}),false);
values['rs-min']='3';values['rs-period']='60';
assert.equal(context.matchesFilters(asset),false);
values['rs-period']='20';assert.equal(context.matchesFilters(asset),true);
values['liquidity-min']='7';assert.equal(context.matchesFilters(asset),false);
values['liquidity-min']='6';values['close-min']='81';assert.equal(context.matchesFilters(asset),false);
values['close-min']='80';assert.equal(context.matchesFilters(asset),true);
assert.equal(context.matchesFilters({...asset,relativeStrength20:null}),false);
assert.equal(context.matchesFilters({...asset,liquidityCurrency:null}),false);
values['rs-min']='';values['liquidity-min']='';values['close-min']='';values['filter-mode']='or';types=['breakout','liquidity'];
assert.equal(context.matchesFilters({...asset,historyStale:true,signals:[{type:'breakout'},{type:'liquidity'}]}),true);
values['filter-mode']='and';values['liquidity-min']='2';types=['liquidity'];
assert.equal(context.matchesFilters({...asset,avgTurnover20:3e6,signals:[]}),true);
console.log('Quality filters: RS windows, currency thresholds, strong close, stale data and OR semantics passed');
